-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
DROP TABLE IF EXISTS "Products" CASCADE;
DROP TABLE IF EXISTS "Contracts" CASCADE;
DROP TABLE IF EXISTS "Storages" CASCADE;
DROP TABLE IF EXISTS "Storages_types" CASCADE;
DROP TABLE IF EXISTS "Racks" CASCADE;
DROP TABLE IF EXISTS "Clients" CASCADE;
DROP TABLE IF EXISTS "Rooms" CASCADE;

CREATE TABLE IF NOT EXISTS "Rooms"
(
    room_id serial,
    room_name character varying(128) NOT NULL,
    volume numeric NOT NULL DEFAULT 1,
    min_temp numeric NOT NULL DEFAULT -30,
    max_temp numeric NOT NULL DEFAULT 30,
    max_humid numeric NOT NULL DEFAULT 0,
    min_humid numeric NOT NULL DEFAULT 100,
    PRIMARY KEY (room_id),
    CONSTRAINT chk_room_volume_positive CHECK (volume > 0),
    CONSTRAINT chk_room_temp_range CHECK (min_temp <= max_temp),
    CONSTRAINT chk_room_humid_range CHECK (min_humid <= max_humid),
    CONSTRAINT chk_room_temp_bounds CHECK (min_temp >= -50 AND max_temp <= 60),
    CONSTRAINT chk_room_humid_bounds CHECK (min_humid >= 0 AND max_humid <= 100),
    CONSTRAINT chk_room_min_humid_valid CHECK (min_humid >= 0),
    CONSTRAINT chk_room_max_humid_valid CHECK (max_humid <= 100)
);

CREATE TABLE IF NOT EXISTS "Racks"
(
    shelf_id serial,
    room_id integer NOT NULL,
    capacity integer NOT NULL,
    max_weight numeric NOT NULL,
    client_id integer,
    PRIMARY KEY (shelf_id),
    CONSTRAINT chk_rack_capacity_positive CHECK (capacity > 0),
    CONSTRAINT chk_rack_max_weight_positive CHECK (max_weight > 0)
);

CREATE TABLE IF NOT EXISTS "Storages"
(
    storage_id serial,
    shelf_id integer NOT NULL,
    type integer NOT NULL,
    PRIMARY KEY (storage_id)
);

CREATE TABLE IF NOT EXISTS "Clients"
(
    client_id serial,
    client_name character varying NOT NULL,
    bak_requisites character varying NOT NULL,
    PRIMARY KEY (client_id),
    CONSTRAINT chk_client_name_not_empty CHECK (client_name <> ''),
    CONSTRAINT chk_client_requisites_not_empty CHECK (bak_requisites <> '')
);

CREATE TABLE IF NOT EXISTS "Contracts"
(
    contract_id serial,
    client_id integer NOT NULL,
    expiry_date time with time zone NOT NULL,
    PRIMARY KEY (contract_id),
    CONSTRAINT chk_contract_expiry_future CHECK (expiry_date > CURRENT_TIME)
);

CREATE TABLE IF NOT EXISTS "Products"
(
    product_id serial,
    name character varying NOT NULL,
    height numeric NOT NULL,
    width numeric NOT NULL,
    length numeric NOT NULL,
    contract_id integer NOT NULL,
    storage_id integer NOT NULL,
    max_temp numeric,
    min_temp numeric,
    max_humid numeric,
    min_humid numeric,
    weight numeric NOT NULL,
    receipt_date time with time zone NOT NULL,
    PRIMARY KEY (product_id),
    CONSTRAINT chk_product_dimensions_positive CHECK (height > 0 AND width > 0 AND length > 0),
    CONSTRAINT chk_product_weight_positive CHECK (weight > 0),
    CONSTRAINT chk_product_temp_range CHECK (min_temp IS NULL OR max_temp IS NULL OR min_temp <= max_temp),
    CONSTRAINT chk_product_humid_range CHECK (min_humid IS NULL OR max_humid IS NULL OR min_humid <= max_humid),
    CONSTRAINT chk_product_temp_bounds CHECK (
        (min_temp IS NULL OR min_temp >= -50) AND 
        (max_temp IS NULL OR max_temp <= 60)
    ),
    CONSTRAINT chk_product_humid_bounds CHECK (
        (min_humid IS NULL OR min_humid >= 0) AND 
        (max_humid IS NULL OR max_humid <= 100)
    ),
    CONSTRAINT chk_product_receipt_date_valid CHECK (receipt_date <= CURRENT_TIME)
);

CREATE TABLE IF NOT EXISTS "Storages_types"
(
    type_id serial,
    hight numeric NOT NULL,
    width numeric NOT NULL,
    lenght numeric NOT NULL,
    max_weight numeric NOT NULL,
    PRIMARY KEY (type_id),
    CONSTRAINT chk_storage_type_dimensions_positive CHECK (hight > 0 AND width > 0 AND lenght > 0),
    CONSTRAINT chk_storage_type_max_weight_positive CHECK (max_weight > 0)
);

-- Foreign key constraints with ON DELETE CASCADE for better data integrity
ALTER TABLE IF EXISTS "Racks"
    ADD CONSTRAINT room_id FOREIGN KEY (room_id)
    REFERENCES "Rooms" (room_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS "Storages"
    ADD CONSTRAINT shelf_id FOREIGN KEY (shelf_id)
    REFERENCES "Racks" (shelf_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS "Storages"
    ADD CONSTRAINT type_id FOREIGN KEY (type)
    REFERENCES "Storages_types" (type_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS "Contracts"
    ADD CONSTRAINT client_id FOREIGN KEY (client_id)
    REFERENCES "Clients" (client_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS "Products"
    ADD CONSTRAINT storage_id FOREIGN KEY (storage_id)
    REFERENCES "Storages" (storage_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS "Products"
    ADD CONSTRAINT contract_id FOREIGN KEY (contract_id)
    REFERENCES "Contracts" (contract_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;

ALTER TABLE "Rooms" 
    ADD CONSTRAINT uk_rooms_name UNIQUE (room_name);

ALTER TABLE "Clients" 
    ADD CONSTRAINT uk_clients_name UNIQUE (client_name);

ALTER TABLE "Storages" 
    ADD CONSTRAINT uk_storage_location UNIQUE (shelf_id, storage_id);

END;
